INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
INFO:telethon.client.users:Phone migrated to 4
INFO:telethon.client.telegrambaseclient:Reconnecting to new data center 4
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.51:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.51:443/TcpFull complete!
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
INFO:root:[https://t.me/lobelia4cosmetics] Scraped 1000 messages.
ERROR:root:Error scraping https://t.me/lobelia4cosmetics: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'Data\\raw\\telegram_messages\\2025-07-12\\https:\\t.me\\lobelia4cosmetics'
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
ERROR:root:Error scraping https://t.me/tikvahpharma: database is locked
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-26' coro=<Connection._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:316> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-27' coro=<Connection._recv_loop() running at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:361> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-28' coro=<MTProtoSender._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:446> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-29' coro=<MTProtoSender._recv_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:497> wait_for=<Future cancelled>>
INFO:root:[lobelia4cosmetics] Scraped 1000 messages.
ERROR:root:Error scraping lobelia4cosmetics: Object of type datetime is not JSON serializable
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
ERROR:root:Error scraping tikvahpharma: database is locked
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
ERROR:root:Error scraping lobelia4cosmetics: database is locked
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
ERROR:root:Error scraping tikvahpharma: database is locked
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-80' coro=<Connection._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:316> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-81' coro=<Connection._recv_loop() running at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:361> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-82' coro=<MTProtoSender._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:446> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-83' coro=<MTProtoSender._recv_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:497> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-129' coro=<Connection._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:316> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-130' coro=<Connection._recv_loop() running at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:361> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-131' coro=<MTProtoSender._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:446> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-132' coro=<MTProtoSender._recv_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:497> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-134' coro=<Connection._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:316> wait_for=<Future cancelled>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-135' coro=<Connection._recv_loop() running at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\connection\connection.py:361> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-136' coro=<MTProtoSender._send_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:446> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-137' coro=<MTProtoSender._recv_loop() done, defined at d:\KAIM 5,6,7\Week-7\Technical\Shipping-Data-from-Raw-Telegram-Data\.venv\Lib\site-packages\telethon\network\mtprotosender.py:497> wait_for=<Future cancelled>>
WARNING:telethon.network.connection.connection:Server closed the connection: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:telethon.network.mtprotosender:Connection closed while receiving data: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:telethon.network.mtprotosender:Closing current connection to begin reconnect...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.91:443/TcpFull...
INFO:telethon.network.connection.connection:<class 'ConnectionResetError'> during disconnect: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:telethon.network.mtprotosender:Connection to 149.154.167.91:443/TcpFull complete!
INFO:telethon.client.updates:Cannot get difference since the account is not logged in: AuthKeyUnregisteredError
INFO:telethon.client.updates:Cannot get difference since the account is not logged in: AuthKeyUnregisteredError
INFO:telethon.network.mtprotosender:Disconnecting from 149.154.167.91:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from 149.154.167.91:443/TcpFull complete!
